"""Add notification and research list tables

Revision ID: 37d59c10c439
Revises: 
Create Date: 2026-06-07 05:52:23.995929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37d59c10c439'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_research_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_symbol', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('impact_level', sa.String(length=20), nullable=False),
    sa.Column('short_term_outlook', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_research_reports_company_symbol'), 'ai_research_reports', ['company_symbol'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('whatsapp_number', sa.String(length=30), nullable=True),
    sa.Column('notification_preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_symbol'), 'notifications', ['symbol'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('research_list',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stock_symbol', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'stock_symbol', name='uq_user_stock_symbol')
    )
    op.create_index(op.f('ix_research_list_stock_symbol'), 'research_list', ['stock_symbol'], unique=False)
    op.create_index(op.f('ix_research_list_user_id'), 'research_list', ['user_id'], unique=False)
    op.alter_column('companies', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               comment='Ticker symbol, e.g. RELIANCE.NS',
               existing_nullable=False)
    op.alter_column('companies', 'exchange',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='NSE, BSE, NYSE, NASDAQ …')
    op.alter_column('companies', 'ceo',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('companies', 'headquarters',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('companies', 'website',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('companies_symbol_key'), 'companies', type_='unique')
    op.create_index(op.f('ix_companies_symbol'), 'companies', ['symbol'], unique=True)
    op.alter_column('company_relationships', 'parent_company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('company_relationships', 'child_company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('company_relationships', 'relationship_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               nullable=False,
               comment='subsidiary | competitor | investor | supply_chain')
    op.alter_column('company_relationships', 'ownership_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               comment='Ownership stake (nullable for non-equity links)',
               existing_nullable=True)
    op.alter_column('company_relationships', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_company_relationships_child_company_id'), 'company_relationships', ['child_company_id'], unique=False)
    op.create_index(op.f('ix_company_relationships_parent_company_id'), 'company_relationships', ['parent_company_id'], unique=False)
    op.alter_column('financials', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('financials', 'period_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               nullable=False,
               comment='quarterly | annual')
    op.alter_column('financials', 'period_end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('financials', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_financials_company_id'), 'financials', ['company_id'], unique=False)
    op.add_column('forex_rates', sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('forex_rates', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('forex_rates', 'base_currency',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=5),
               comment='e.g. USD',
               existing_nullable=False)
    op.alter_column('forex_rates', 'target_currency',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=5),
               comment='e.g. INR',
               existing_nullable=False)
    op.alter_column('forex_rates', 'rate',
               existing_type=sa.NUMERIC(precision=16, scale=6),
               type_=sa.Numeric(precision=18, scale=6),
               nullable=False)
    op.create_index(op.f('ix_forex_rates_base_currency'), 'forex_rates', ['base_currency'], unique=False)
    op.create_index(op.f('ix_forex_rates_target_currency'), 'forex_rates', ['target_currency'], unique=False)
    op.drop_column('forex_rates', 'timestamp')
    op.alter_column('news', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('news', 'headline',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('news', 'source',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('news', 'sentiment_score',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               comment='Range -1.000 (bear) to +1.000 (bull)',
               existing_nullable=True)
    op.alter_column('news', 'sentiment_label',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               comment='positive | negative | neutral',
               existing_nullable=True)
    op.alter_column('news', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_news_company_id'), 'news', ['company_id'], unique=False)
    op.alter_column('ownership', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('ownership', 'as_of_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('ownership', 'promoter_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('ownership', 'fii_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               comment='Foreign Institutional Investors',
               existing_nullable=True)
    op.alter_column('ownership', 'dii_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               comment='Domestic Institutional Investors',
               existing_nullable=True)
    op.alter_column('ownership', 'retail_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('ownership', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_ownership_company_id'), 'ownership', ['company_id'], unique=False)
    op.alter_column('stock_prices', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('stock_prices', 'open',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=18, scale=4),
               nullable=False)
    op.alter_column('stock_prices', 'high',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=18, scale=4),
               nullable=False)
    op.alter_column('stock_prices', 'low',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=18, scale=4),
               nullable=False)
    op.alter_column('stock_prices', 'close',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=18, scale=4),
               nullable=False)
    op.alter_column('stock_prices', 'volume',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=20, scale=0),
               nullable=False)
    op.alter_column('stock_prices', 'is_live',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='True if fetched in real-time',
               existing_server_default=sa.text('false'))
    op.alter_column('stock_prices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_stock_prices_company_id'), 'stock_prices', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_prices_timestamp'), 'stock_prices', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_prices_timestamp'), table_name='stock_prices')
    op.drop_index(op.f('ix_stock_prices_company_id'), table_name='stock_prices')
    op.alter_column('stock_prices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stock_prices', 'is_live',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='True if fetched in real-time',
               existing_server_default=sa.text('false'))
    op.alter_column('stock_prices', 'volume',
               existing_type=sa.Numeric(precision=20, scale=0),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('stock_prices', 'close',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=12, scale=4),
               nullable=True)
    op.alter_column('stock_prices', 'low',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=12, scale=4),
               nullable=True)
    op.alter_column('stock_prices', 'high',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=12, scale=4),
               nullable=True)
    op.alter_column('stock_prices', 'open',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=12, scale=4),
               nullable=True)
    op.alter_column('stock_prices', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_ownership_company_id'), table_name='ownership')
    op.alter_column('ownership', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ownership', 'retail_pct',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('ownership', 'dii_pct',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Domestic Institutional Investors',
               existing_nullable=True)
    op.alter_column('ownership', 'fii_pct',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Foreign Institutional Investors',
               existing_nullable=True)
    op.alter_column('ownership', 'promoter_pct',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('ownership', 'as_of_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('ownership', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_news_company_id'), table_name='news')
    op.alter_column('news', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('news', 'sentiment_label',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='positive | negative | neutral',
               existing_nullable=True)
    op.alter_column('news', 'sentiment_score',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               comment=None,
               existing_comment='Range -1.000 (bear) to +1.000 (bull)',
               existing_nullable=True)
    op.alter_column('news', 'source',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('news', 'headline',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('news', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('forex_rates', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_forex_rates_target_currency'), table_name='forex_rates')
    op.drop_index(op.f('ix_forex_rates_base_currency'), table_name='forex_rates')
    op.alter_column('forex_rates', 'rate',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=16, scale=6),
               nullable=True)
    op.alter_column('forex_rates', 'target_currency',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='e.g. INR',
               existing_nullable=False)
    op.alter_column('forex_rates', 'base_currency',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='e.g. USD',
               existing_nullable=False)
    op.drop_column('forex_rates', 'created_at')
    op.drop_column('forex_rates', 'fetched_at')
    op.drop_index(op.f('ix_financials_company_id'), table_name='financials')
    op.alter_column('financials', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('financials', 'period_end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('financials', 'period_type',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='quarterly | annual')
    op.alter_column('financials', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_company_relationships_parent_company_id'), table_name='company_relationships')
    op.drop_index(op.f('ix_company_relationships_child_company_id'), table_name='company_relationships')
    op.alter_column('company_relationships', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('company_relationships', 'ownership_pct',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Ownership stake (nullable for non-equity links)',
               existing_nullable=True)
    op.alter_column('company_relationships', 'relationship_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               comment=None,
               existing_comment='subsidiary | competitor | investor | supply_chain')
    op.alter_column('company_relationships', 'child_company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('company_relationships', 'parent_company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_companies_symbol'), table_name='companies')
    op.create_unique_constraint(op.f('companies_symbol_key'), 'companies', ['symbol'], postgresql_nulls_not_distinct=False)
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'website',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('companies', 'headquarters',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('companies', 'ceo',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('companies', 'exchange',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='NSE, BSE, NYSE, NASDAQ …')
    op.alter_column('companies', 'symbol',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Ticker symbol, e.g. RELIANCE.NS',
               existing_nullable=False)
    op.drop_index(op.f('ix_research_list_user_id'), table_name='research_list')
    op.drop_index(op.f('ix_research_list_stock_symbol'), table_name='research_list')
    op.drop_table('research_list')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_symbol'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ai_research_reports_company_symbol'), table_name='ai_research_reports')
    op.drop_table('ai_research_reports')
    # ### end Alembic commands ###
