export default function RiskWarning() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 py-12">
      {/* Header */}
      <div className="mb-12">
        <div className="text-xs font-bold uppercase tracking-widest text-negative mb-4">Risk Warning</div>
        <h1 className="text-4xl font-extrabold text-text-primary mb-4">Risk Warning</h1>
        <p className="text-text-secondary">
          Last Updated: <strong>April 10, 2026</strong>
        </p>
        <div className="mt-6 p-5 bg-red-50 border-l-4 border-negative rounded-xl text-sm text-red-900 leading-relaxed">
          <strong className="text-base">⚠️ Important Notice:</strong> Trading and investing in financial instruments involves substantial risk of loss. Please read this warning carefully before using ArthiQ. This platform does not provide financial advice.
        </div>
      </div>

      {/* Sections */}
      <div className="space-y-8">

        <div className="glass-card p-6 md:p-8 border-l-4 border-negative">
          <h2 className="text-lg font-bold text-text-primary mb-4">General Risk of Investing</h2>
          <p className="text-text-secondary leading-relaxed text-sm mb-3">
            The value of financial instruments — including stocks, ETFs, mutual funds, derivatives, and forex — can go up as well as down. You may not get back the amount you originally invested. Past performance of any instrument, strategy, or market is not a reliable indicator of future results.
          </p>
          <p className="text-text-secondary leading-relaxed text-sm">
            Investing in the Indian stock market (NSE/BSE) involves market risk, liquidity risk, and regulatory risk. Markets can be volatile and can be affected by domestic and global macroeconomic factors, government policy, RBI decisions, FII/DII flows, and geopolitical events.
          </p>
        </div>

        <div className="glass-card p-6 md:p-8">
          <h2 className="text-lg font-bold text-text-primary mb-4">AI Insights Are Not Financial Advice</h2>
          <p className="text-text-secondary leading-relaxed text-sm mb-3">
            ArthiQ uses AI (GPT-4o-mini) to generate market insights, price outlooks, and analysis of why stocks moved. These insights are <strong className="text-text-primary">generated by an algorithm</strong> and are provided for informational and educational purposes only.
          </p>
          <p className="text-text-secondary leading-relaxed text-sm mb-3">
            AI-generated content may contain errors, hallucinations, or inaccuracies, especially during fast-moving market conditions. The AI does not have access to real-time insider information and its analysis may lag market developments.
          </p>
          <p className="text-text-secondary leading-relaxed text-sm">
            <strong className="text-text-primary">Do not make any investment decision solely based on ArthiQ's AI insights.</strong> Always verify information independently and consult a SEBI-registered investment advisor before investing.
          </p>
        </div>

        <div className="glass-card p-6 md:p-8">
          <h2 className="text-lg font-bold text-text-primary mb-4">Data Accuracy and Delays</h2>
          <p className="text-text-secondary leading-relaxed text-sm mb-3">
            Stock price and market data displayed on ArthiQ may be delayed by up to 15 minutes from NSE/BSE exchange feeds. ArthiQ does not guarantee the accuracy, completeness, or timeliness of any data displayed on this platform.
          </p>
          <p className="text-text-secondary leading-relaxed text-sm">
            Data sourced from third-party providers, news APIs, and AI-generated content may be incomplete, inaccurate, or outdated. For real-time, accurate trading data, always refer to the official NSE (nseindia.com) or BSE (bseindia.com) websites or your licensed broker's platform.
          </p>
        </div>

        <div className="glass-card p-6 md:p-8">
          <h2 className="text-lg font-bold text-text-primary mb-4">Sectoral and Concentration Risk</h2>
          <p className="text-text-secondary leading-relaxed text-sm">
            Focusing investment in a single sector, company, or asset class significantly increases your risk. ArthiQ's AI analysis may highlight specific sectors or stocks which should not be interpreted as a concentration recommendation. Diversification across asset classes, sectors, and geographies is a fundamental principle of prudent investing.
          </p>
        </div>

        <div className="glass-card p-6 md:p-8">
          <h2 className="text-lg font-bold text-text-primary mb-4">Regulatory Environment</h2>
          <p className="text-text-secondary leading-relaxed text-sm mb-3">
            The Indian financial markets are regulated by SEBI (Securities and Exchange Board of India), RBI (Reserve Bank of India), and other regulatory bodies. Regulatory changes, policy decisions, and legal developments can significantly impact the performance of financial instruments.
          </p>
          <p className="text-text-secondary leading-relaxed text-sm">
            ArthiQ is not a SEBI-registered investment advisor, research analyst, or broker. We are a technology platform providing market data and AI-powered analysis. We operate under applicable Indian information technology laws.
          </p>
        </div>

        <div className="glass-card p-6 md:p-8">
          <h2 className="text-lg font-bold text-text-primary mb-4">Your Responsibility</h2>
          <p className="text-text-secondary leading-relaxed text-sm mb-3">
            Before making any investment decision, you should:
          </p>
          <ul className="list-disc list-inside space-y-2 text-sm text-text-secondary">
            <li>Conduct your own thorough due diligence and research</li>
            <li>Consult with a SEBI-registered investment advisor or financial planner</li>
            <li>Understand your own risk tolerance and investment horizon</li>
            <li>Read the fund offer document, company disclosures, and exchange filings</li>
            <li>Only invest money you can afford to lose</li>
            <li>Diversify your investments across multiple asset classes</li>
          </ul>
        </div>

        <div className="glass-card p-6 md:p-8">
          <h2 className="text-lg font-bold text-text-primary mb-4">Limitation of Liability</h2>
          <p className="text-text-secondary leading-relaxed text-sm">
            ArthiQ and its directors, officers, employees, partners, and agents shall not be liable for any direct, indirect, incidental, special, or consequential financial losses incurred because of reliance on content or data available on this platform. By continuing to use ArthiQ, you acknowledge that you have read this Risk Warning and accept full responsibility for your own investment decisions.
          </p>
        </div>

      </div>

      {/* Footer Note */}
      <div className="mt-12 text-center glass-card p-6">
        <p className="text-sm text-text-secondary">
          If you have concerns about investment risk, please consult a{' '}
          <a href="https://www.sebi.gov.in" target="_blank" rel="noopener noreferrer" className="text-saffron font-semibold hover:underline">
            SEBI-registered investment advisor
          </a>
          {' '}before proceeding. For questions, contact{' '}
          <a href="mailto:arthiqaiofficial@gmail.com" className="text-saffron font-semibold hover:underline">
            arthiqaiofficial@gmail.com
          </a>
        </p>
      </div>
    </div>
  )
}
